#!/usr/bin/env python3
# Nr_Solver.py version 17
"""
Lehmer-Størmer enumerator by PARI Pell equation solver

Purpose
-------
Enumerate and verify candidates for prime-complete products of consecutive integers

    N_r(m) = m (m+1) ... (m+r-1)

under the Størmer-Lehmer S-unit framework.

High-level idea (runlength, r=2 for m(m+1))
---------------------
For a fixed prime set P = {p1,...,p_ω}, we enumerate all m such that m and m+1
are P-smooth. Each such m arises from a Pell-type equation:

    x^2 - (2q) y^2 = 1

where q is a squarefree product of primes from P (encoded by a bitmask).
Given a minimal solution (x1,y1) for D=2q, all solutions are generated by
powers of (x1 + y1*sqrt(D)). Each solution yields a candidate

    m = (x - 1)/2,

which we then filter for smoothness and finally certify prime-completeness by
factorization and exact prime-support comparison.

Implementation notes
--------------------
* Pell solver: continued fractions in GP (PARI/GP), avoiding algebraic-number
  field basis pitfalls. The GP routine pellxy(D) returns integer (x,y) with
  x^2 - D y^2 = 1.
* Concurrency: multiprocessing over mask ranges (or "striped" offsets). For
  ω -> ω+1 incremental enumeration, only the "new half" of masks is processed
  (those that include the new prime), while previously found m values are
  retained.
* Audit trail: for each (r, ω) run we write:
    - S-file of candidate m values
    - verification CSV (factorizations + prime-complete hit flag)
    - run log (progress + parameters)
    - summary JSON (hashes + environment + completeness indicators)

Reproducibility / certification
-------------------------------
For referee-grade certification, preserve:
  (1) the exact script version (script SHA256, optional git commit),
  (2) the exact command line,
  (3) tool versions (Python/GP),
  (4) all produced artifacts with SHA256 hashes, and
  (5) completeness indicators (unprocessed_masks == 0, cum_failed == 0).

How to install / run (macOS example)
------------------------------------
1) Install PARI/GP (Homebrew):
       brew install pari
2) Run a sweep (m(m+1), ω=8..20), full enumeration:
       python3 Nr_Solver.py --outdir audit_runs --runlength 2 \
         --start_omega 8 --end_omega 20 --workers 10 --chunk_masks 16 \
         --gp_path /opt/homebrew/bin/gp --assertions
3) Run high-omega sweep with early rejection on m(m+1) (vastly faster for ω≥17):
       python3 Nr_Solver.py --outdir audit_runs --runlength 2 \
         --start_omega 17 --end_omega 30 --workers 10 --chunk_masks 16 \
         --max_m 10000000000000000000000000 \
         --gp_path /opt/homebrew/bin/gp --assertions

Use --version to print a machine-readable environment/version block.

Version 10 changes (Feb 20 2026)
---------------------------------
* Added --max_m for provably correct early rejection:
  - q-bound pre-filter: skips GP call when q > 2*max_m*(max_m+1)
  - GP-side bailout: continued fraction aborts when convergent p > 2*max_m+1
  - Fundamental solution gate: skips iterate loop when x1 > 2*max_m+1
  - Iterate early-break: breaks loop when x > 2*max_m+1
* GP pellxy(D, max_x) now accepts optional max_x parameter for early bailout
  inside the continued fraction computation, avoiding enormous convergents
* All optimizations are provably complete: no valid smooth pair can be missed
* New audit trail fields: masks_skipped_q_bound, masks_skipped_x1_bound,
  masks_skipped_gp_bailout, iterates_early_break
* Handshake self-test now verifies both solution correctness and bailout behavior


Version 17 changes (Feb 27 2026)
---------------------------------
* Corrected iterate bound: L = max(3, pmax) instead of max(3, (pmax+1)//2).
  The Størmer-Lehmer theorem (via the primitive divisor theorem of
  Bilu-Hanrot-Voutier 2001) guarantees that for the Pell sequence
  x_n^2 - 2q*y_n^2 = 1, if m = (x_n - 1)/2 is P-smooth then n <= pmax.
  The prior half-pmax bound was conservative in the wrong direction —
  it was too small to guarantee completeness. This fix closes the gap
  between the computational search and a formally complete enumeration.

By Ken Clements, Feb 16 2026
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import math
import os
import re
import subprocess
import sys
import platform

# Disable Python's safety limit on int() string parsing for trusted local computation.
try:
    sys.set_int_max_str_digits(0)
except Exception:
    pass

import time
from dataclasses import dataclass
from datetime import datetime, timezone
from multiprocessing import get_context
from typing import Dict, List, Optional, Set, Tuple


program_name, program_version = "Nr_Solver", 16


# ----------------------------- switches (set by args) -----------------------------
DEBUG = False
ASSERTIONS = False
ENV: Dict[str, object] = {}


# ----------------------------- small utilities -----------------------------
def utc_now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()

def ensure_dir(path: str) -> None:
    os.makedirs(path, exist_ok=True)

def sha256_file(path: str) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def read_self_source(path: str) -> bytes:
    with open(path, "rb") as f:
        return f.read()

def sha256_bytes(b: bytes) -> str:
    h = hashlib.sha256()
    h.update(b)
    return h.hexdigest()

def get_git_commit() -> Optional[str]:
    # Best effort: if this file is inside a git repo, return HEAD commit hash.
    try:
        r = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            capture_output=True,
            text=True,
            check=True,
        )
        s = (r.stdout or "").strip()
        return s if s else None
    except Exception:
        return None

def get_gp_version(gp_path: str) -> Optional[str]:
    # Best effort: ask GP for version() in quiet mode.
    try:
        r = subprocess.run(
            [gp_path, "-q"],
            input="print(version());\nquit\n",
            capture_output=True,
            text=True,
            check=True,
        )
        # Use last non-empty line
        lines = [ln.strip() for ln in (r.stdout or "").splitlines() if ln.strip()]
        return lines[-1] if lines else None
    except Exception:
        return None

def env_block(gp_path: str, script_path: str, argv: List[str]) -> Dict[str, object]:
    src = read_self_source(script_path)
    return {
        "script_path": os.path.abspath(script_path),
        "script_sha256": sha256_bytes(src),
        "git_commit": get_git_commit(),
        "command_line": " ".join(argv),
        "python_version": sys.version.replace("\n", " "),
        "platform": platform.platform(),
        "gp_path": gp_path,
        "gp_version": get_gp_version(gp_path),
    }


def primes_first_n(n: int) -> List[int]:
    """Return the first n primes (sympy-free).

    For this project n is small (typically <= 30), so a simple incremental
    trial-division generator is more than fast enough and removes the SymPy
    dependency.
    """
    if n <= 0:
        return []
    primes: List[int] = []
    candidate = 2
    while len(primes) < n:
        is_prime = True
        r = int(math.isqrt(candidate))
        for p in primes:
            if p > r:
                break
            if candidate % p == 0:
                is_prime = False
                break
        if is_prime:
            primes.append(candidate)
        candidate += 1 if candidate == 2 else 2  # 2, then odds only
    return primes

def load_int_list(path: str) -> List[int]:
    vals: List[int] = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            s = line.strip()
            if not s or s.startswith("#"):
                continue
            vals.append(int(s))
    return sorted(set(vals))

def write_int_list(path: str, vals: List[int]) -> None:
    with open(path, "w", encoding="utf-8") as f:
        for v in sorted(vals):
            f.write(f"{v}\n")

def is_P_smooth(x: int, primes: Tuple[int, ...]) -> bool:
    if x <= 0:
        return False
    for p in primes:
        while x % p == 0:
            x //= p
    return x == 1

def factor_merge(a: Dict[int, int], b: Dict[int, int]) -> Dict[int, int]:
    out = dict(a)
    for p, e in b.items():
        out[p] = out.get(p, 0) + e
    return out

def support_tuple(f: Dict[int, int]) -> Tuple[int, ...]:
    return tuple(sorted(f.keys()))

def format_factorization(f: Dict[int, int]) -> str:
    items = sorted(f.items())
    return " * ".join(f"{p}^{e}" for p, e in items) if items else "1"

def factor_over_P(n: int, primes: Tuple[int, ...]) -> Tuple[Dict[int, int], int]:
    """Factor n over the given prime basis.

    Returns (exponent_dict, remainder). If remainder != 1, then n has at least one
    prime factor not in 'primes'. This is used both for smoothness checks and for
    building the exact factorization of N_r over the target prime set.
    """
    rem = n
    out: Dict[int, int] = {}
    for p in primes:
        if rem % p == 0:
            e = 0
            while rem % p == 0:
                rem //= p
                e += 1
            out[p] = e
        if rem == 1:
            break
    return out, rem


# ----------------------------- PARI/GP interface (why and how) -----------------------------
# PARI/GP is a mature, high-performance system for computational number theory. The PARI library (libpari) provides
# fast big-integer arithmetic and specialized algorithms for primes, modular arithmetic, continued fractions, and
# Pell-type Diophantine problems; GP is PARI’s small scripting language and REPL front-end. In this project we use
# PARI/GP as a “number theory coprocessor”: Python handles orchestration (parallel mask scheduling, I/O, audit logs,
# verification), while GP performs the heavy inner-kernel arithmetic on very large integers.
#
# The integration is intentionally simple and auditable. We launch `gp -q` as a subprocess and keep it alive, then
# send GP source code over stdin to define a single entrypoint `pellxy(D)` (plus helpers). Each evaluation is wrapped
# in sentinel markers (__BEGIN__/__END__) so Python can parse the response unambiguously from stdout. A startup
# handshake self-test (e.g. pellxy(46) and verifying x^2 - D*y^2 = 1) ensures the GP side is correctly initialized.
#
# The GP code implements a Pell solver via continued fractions of sqrt(D). For each D=2q (q from a prime-subset mask),
# we compute the minimal integer solution (x1,y1) to x^2 - D*y^2 = 1 by iterating convergents until the identity
# holds. Python then iterates powers of the fundamental solution using the standard recurrence
#   (x',y') = (x1*x + D*y1*y,  x1*y + y1*x),
# which preserves x^2 - D*y^2 = 1 exactly. Each iterate yields a candidate m = (x-1)/2 (when x is odd), which is then
# filtered for P-smoothness (and later checked for prime-completeness by exact factorization and prime-support equality).
# The separation is deliberate: GP supplies certified Pell arithmetic; Python enforces predicates and produces the
# reproducible audit trail (logs + hashes + environment/version metadata).

# ----------------------------- GP / Pell -----------------------------
# v5 FIX: remove bnfnorm (your gp build is choking on it). Use lifted coefficients instead.
_PELLXY_DEF = r"""
/* Return minimal integer [x,y] solving x^2 - D*y^2 = 1  (D positive nonsquare)
   If max_x > 0 and the convergent exceeds max_x before finding the solution,
   return [0,0] as a sentinel (no solution within bound).
   Correctness: convergents p_n of sqrt(D) grow monotonically (p_{n+1} = a*p_n + p_{n-1}
   with a >= 1), so once p_n > max_x, the fundamental solution x >= p_n > max_x. */
pellxy_cf(D, max_x=0)={
  if(D<=0, error("D<=0"));
  if(issquare(D), error("square"));

  my(a0 = sqrtint(D));
  my(m=0, d=1, a=a0);
  my(p0=1, p1=a0);
  my(q0=0, q1=1);

  /* If a0^2-D*1^2==1 (only D=0), not possible here; proceed */
  while(p1^2 - D*q1^2 != 1,
    m = d*a - m;
    d = (D - m^2)/d;
    a = (a0 + m)\d;

    my(p2 = a*p1 + p0);
    my(q2 = a*q1 + q0);
    p0=p1; p1=p2;
    q0=q1; q1=q2;

    /* Early bailout: convergent has exceeded max_x, solution is too large */
    if(max_x > 0 && p1 > max_x, return([0,0]));
  );
  [p1, q1];
};

/* Factor D = d*s^2 with d squarefree and return integer [x,y] for x^2 - D*y^2=1
   If max_x > 0, bail out early when the solution exceeds max_x. */
pellxy(D, max_x=0)={
  if(D<=0, error("D<=0"));
  if(issquare(D), error("square"));

  my(F = factor(D));
  my(P = F[,1], E = F[,2]);
  my(d = 1, s = 1);
  for(i=1, #P,
    my(e = E[i]);
    if(e%2, d *= P[i]);
    s *= P[i]^(e\2);
  );

  my(v = pellxy_cf(d, max_x));
  if(v == [0,0], return([0,0]));   /* propagate bailout sentinel */
  my(a = v[1], b = v[2]); /* a^2 - d*b^2 = 1 */

  if(s==1, return([a,b]));

  /* Need b divisible by s so y=b/s integer for D=d*s^2.
     Multiply by fundamental solution until b ≡ 0 (mod s). */
  my(a1=a, b1=b);
  while(b % s,
    my(aa = a1*a + d*b1*b);
    my(bb = a1*b + b1*a);
    a=aa; b=bb;
    /* Early bailout: a is now x, and iterates only grow */
    if(max_x > 0 && a > max_x, return([0,0]));
  );

  my(y = b/s);
  if(a^2 - D*y^2 != 1, error("internal check failed"));
  [a,y];
};
"""

_BEGIN = "__BEGIN__"
_END = "__END__"
_VEC2_INT_RE = re.compile(r"^\[\s*(-?\d+)\s*,\s*(-?\d+)\s*\]\s*$")

_GP_PROC: Optional[subprocess.Popen] = None
_GP_PATH: str = "gp"


def _gp_kill() -> None:
    global _GP_PROC
    if _GP_PROC is None:
        return
    try:
        _GP_PROC.kill()
    except Exception:
        pass
    _GP_PROC = None


def _gp_start() -> subprocess.Popen:
    p = subprocess.Popen(
        [_GP_PATH, "-q"],
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
    )
    assert p.stdin and p.stdout

    # load definitions
    p.stdin.write(_PELLXY_DEF + "\n")

    # handshake self-test
    p.stdin.write(f'print("{_BEGIN}");\n')
    p.stdin.write("v=pellxy(46); print(v); print(v[1]^2-46*v[2]^2);\n")
    # Bailout self-test: pellxy(46) gives x=24335, so max_x=100 should bail out
    p.stdin.write("vb=pellxy(46, 100); print(vb);\n")
    p.stdin.write(f'print("{_END}");\n')
    p.stdin.flush()

    lines: List[str] = []
    in_block = False
    while True:
        line = p.stdout.readline()
        if line == "":
            raise RuntimeError("gp handshake EOF")
        s = line.rstrip("\n").strip()
        if s == _BEGIN:
            in_block = True
            continue
        if s == _END:
            break
        if in_block:
            lines.append(s)

    if len(lines) < 3:
        raise RuntimeError(f"gp handshake unexpected output: {lines!r}")
    if lines[-2] != "1":
        raise RuntimeError(f"gp handshake failed certification: {lines!r}")
    if lines[-1] != "[0, 0]":
        raise RuntimeError(f"gp handshake bailout test failed (expected [0, 0]): {lines!r}")
    if _VEC2_INT_RE.match(lines[-3]) is None:
        raise RuntimeError(f"gp handshake did not return integer vector: {lines!r}")

    return p


def _gp_eval(expr: str, timeout_sec: float = 0.0) -> str:
    global _GP_PROC
    if _GP_PROC is None:
        _GP_PROC = _gp_start()
    assert _GP_PROC.stdin and _GP_PROC.stdout

    _GP_PROC.stdin.write(f'print("{_BEGIN}");\n')
    _GP_PROC.stdin.write(f"print({expr});\n")
    _GP_PROC.stdin.write(f'print("{_END}");\n')
    _GP_PROC.stdin.flush()

    lines: List[str] = []
    in_block = False
    t0 = time.time()
    while True:
        if timeout_sec and (time.time() - t0) > timeout_sec:
            raise RuntimeError("gp eval timeout")
        line = _GP_PROC.stdout.readline()
        if line == "":
            raise RuntimeError("gp EOF (process died)")
        s = line.rstrip("\n").strip()
        if s == _BEGIN:
            in_block = True
            continue
        if s == _END:
            break
        if in_block:
            lines.append(s)

    return "\n".join(lines).strip()


def _pell_xy_gp(D: int, retries: int = 2, gp_timeout: float = 0.0,
                max_x: int = 0) -> Tuple[int, int, str]:
    """Solve x^2 - D*y^2 = 1 via GP continued fractions.

    If max_x > 0 and the fundamental solution has x > max_x, returns (0, 0, raw)
    as a sentinel indicating the solution exceeds the bound. This avoids computing
    enormous convergents inside GP.
    """
    last_exc: Optional[Exception] = None
    last_out: str = ""
    for _ in range(retries + 1):
        try:
            expr = f"pellxy({D}, {max_x})" if max_x > 0 else f"pellxy({D})"
            out = _gp_eval(expr, timeout_sec=gp_timeout)
            last_out = out

            # reject error banners
            if "***" in out or "error" in out.lower():
                raise RuntimeError(f"gp error banner: {out[:200]!r}")

            m = _VEC2_INT_RE.match(out)
            if not m:
                raise RuntimeError(f"Unexpected gp output format: {out!r}")

            x = int(m.group(1))
            y = int(m.group(2))

            # Handle [0,0] sentinel: solution exceeded max_x bound
            if x == 0 and y == 0:
                return 0, 0, out

            if x * x - D * y * y != 1:
                raise RuntimeError(f"Bad Pell solution: D={D} (x,y)=({x},{y})")

            return x, y, out
        except Exception as e:
            last_exc = e
            _gp_kill()
            continue
    raise RuntimeError(f"gp pellxy failed for D={D}: {last_exc!r}; last_out={last_out[:200]!r}")


# A “mask chunk” is a contiguous block (or small batch) of prime-subset bitmasks that a worker processes as a unit.
# Each bitmask encodes a squarefree subset of the current prime set P = (p1,...,p_omega): bit i is 1 iff p_i is
# included, and the mask maps to q = ∏ p_i. For each q we form the Pell parameter D = 2q and compute the minimal
# solution (x1,y1) to x^2 − D y^2 = 1; iterating that fundamental unit yields candidate m = (x−1)/2 values, which
# are then filtered for P-smoothness (and later prime-completeness). Chunking masks amortizes gp startup/IPC overhead,
# enables dynamic work distribution across CPU cores, and provides a natural unit for retry/requeue when a small
# subset of masks is unusually expensive (“stragglers”) or temporarily fails.

# ----------------------------- mask plumbing -----------------------------
def q_from_mask(mask: int, primes: Tuple[int, ...]) -> int:
    q = 1
    i = 0
    while mask:
        if mask & 1:
            q *= primes[i]
        mask >>= 1
        i += 1
    return q


@dataclass(frozen=True)
class WorkerParams:
    primes: Tuple[int, ...]
    L: int
    r: int
    nze_enabled: bool
    start_mask: int
    end_mask: int
    striped: bool
    step: int
    gp_timeout: float
    max_m: int  # Upper bound on m; 0 = no bound (full enumeration)


@dataclass(frozen=True)
class ChunkTask:
    a: int = 0
    b: int = 0
    offset: int = 0
    masks: Optional[Tuple[int, ...]] = None


@dataclass
class ChunkResult:
    ok: bool
    task: ChunkTask
    ms: List[int]
    tried: int
    failed: int
    failed_masks: List[int]
    elapsed_sec: float
    err_samples: List[str]
    masks_skipped_q_bound: int = 0
    masks_skipped_x1_bound: int = 0
    masks_skipped_gp_bailout: int = 0
    iterates_early_break: int = 0
    candidates_skipped_nze: int = 0
    # Debug-only NZE pruning diagnostics (aggregate-friendly; populated only when DEBUG and NZE enabled)
    nze_missing_prime_hist: Optional[Dict[int, int]] = None
    nze_min_missing_count: Optional[int] = None
    nze_min_missing_m: Optional[int] = None


def _init_worker(gp_path: str, debug: bool, assertions: bool) -> None:
    # Ensure the int() parsing limit is disabled in worker processes too.
    try:
        sys.set_int_max_str_digits(0)
    except Exception:
        pass
    import sys
    try:
        sys.set_int_max_str_digits(0)
    except AttributeError:
        pass
    global _GP_PATH, DEBUG, ASSERTIONS
    _GP_PATH = gp_path
    DEBUG = debug
    ASSERTIONS = assertions


def worker_chunk(args: Tuple[ChunkTask, WorkerParams]) -> ChunkResult:
    task, params = args
    primes = params.primes
    L = params.L
    r = params.r
    nze_enabled = params.nze_enabled
    max_m = params.max_m

    # Pre-compute q-bound: if q > q_ceiling, then even the fundamental
    # Pell solution gives m > max_m.  Proof: from x^2 - 2qy^2 = 1 with
    # y >= 1, x >= sqrt(2q+1), so m = (x-1)/2 >= (sqrt(2q+1)-1)/2.
    # Setting m > max_m gives q > 2*max_m*(max_m+1).
    q_ceiling = 2 * max_m * (max_m + 1) if max_m > 0 else 0
    # x-bound: if x > x_ceiling, then m = (x-1)/2 > max_m.
    x_ceiling = 2 * max_m + 1 if max_m > 0 else 0

    t0 = time.time()
    out: Set[int] = set()
    tried = 0
    failed = 0
    failed_masks: List[int] = []
    err_samples: List[str] = []
    masks_skipped_q_bound = 0
    masks_skipped_x1_bound = 0
    masks_skipped_gp_bailout = 0
    iterates_early_break = 0
    candidates_skipped_nze = 0

    # NZE pruning diagnostics (only populated when DEBUG and NZE enabled)
    nze_hist: Optional[Dict[int, int]] = None
    nze_min_missing: Optional[int] = None
    nze_min_m: Optional[int] = None
    if DEBUG and nze_enabled:
        nze_hist = {}

    def handle_mask(mask: int) -> None:
        nonlocal tried, failed, masks_skipped_q_bound, masks_skipped_x1_bound, masks_skipped_gp_bailout, iterates_early_break, candidates_skipped_nze, nze_min_missing, nze_min_m
        q = q_from_mask(mask, primes)
        if q == 2:
            return

        # --- Optimization 1: q-bound pre-filter ---
        # Skip GP call entirely when q is too large for any solution
        # to satisfy m <= max_m.  Rigorous: m(m+1) = qY^2/2 >= q/2,
        # so if q > 2*max_m*(max_m+1), then m > max_m for all iterates.
        if q_ceiling > 0 and q > q_ceiling:
            masks_skipped_q_bound += 1
            return

        D = 2 * q
        tried += 1
        try:
            x1, y1, _raw = _pell_xy_gp(D, retries=2, gp_timeout=params.gp_timeout,
                                        max_x=x_ceiling)

            # Handle GP-side early bailout: solution exceeded max_x
            if x1 == 0 and y1 == 0:
                masks_skipped_gp_bailout += 1
                return

            if ASSERTIONS:
                assert x1 * x1 - D * y1 * y1 == 1

            # --- Optimization 2: fundamental solution gate ---
            # If even the first iterate gives m > max_m, all subsequent
            # iterates are larger (Pell iterates grow monotonically).
            # Skip the entire iterate loop.
            # (This is a backstop; the GP-side bailout should catch most cases.)
            if x_ceiling > 0 and x1 > x_ceiling:
                masks_skipped_x1_bound += 1
                return

            x, y = x1, y1
            for _ in range(L):
                # --- Optimization 3: iterate early-break ---
                # Pell iterates grow monotonically: once x > x_ceiling
                # (equivalently m > max_m), all subsequent iterates exceed it.
                if x_ceiling > 0 and x > x_ceiling:
                    iterates_early_break += 1
                    break
                if ((x - 1) & 1) == 0:
                    m = (x - 1) // 2
                    if m > 0:
                        # Require P-smoothness for all r consecutive multipliers
                        if all(is_P_smooth(m + j, primes) for j in range(r)):
                            if not nze_enabled:
                                out.add(m)
                            else:
                                # NZE pruning: require full prime coverage (prime-complete support)
                                fNr: Dict[int, int] = {}
                                ok_cov = True
                                for j in range(r):
                                    fj, rem = factor_over_P(m + j, primes)
                                    if rem != 1:
                                        ok_cov = False
                                        break
                                    fNr = factor_merge(fNr, fj)
                                if ok_cov and support_tuple(fNr) == primes:
                                    out.add(m)
                                else:
                                    candidates_skipped_nze += 1
                                    if DEBUG and nze_hist is not None and ok_cov:
                                        # Record which primes are missing for this rejected smooth candidate.
                                        supp = set(support_tuple(fNr))
                                        missing = [p for p in primes if p not in supp]
                                        mc = len(missing)
                                        if nze_min_missing is None or mc < nze_min_missing or (mc == nze_min_missing and (nze_min_m is None or m < nze_min_m)):
                                            nze_min_missing = mc
                                            nze_min_m = m
                                        for p in missing:
                                            nze_hist[p] = nze_hist.get(p, 0) + 1

                nx = x1 * x + D * y1 * y
                ny = x1 * y + y1 * x
                x, y = nx, ny

                if ASSERTIONS:
                    assert x * x - D * y * y == 1

        except Exception as e:
            failed += 1
            failed_masks.append(mask)
            if len(err_samples) < 10:
                if DEBUG:
                    err_samples.append(f"mask={mask} q={q} D={D} err={repr(e)}")
                else:
                    err_samples.append(repr(e))

    if task.masks is not None:
        for mask in task.masks:
            handle_mask(mask)
    elif params.striped:
        mask = params.start_mask + task.offset
        while mask < params.end_mask:
            handle_mask(mask)
            mask += params.step
    else:
        for mask in range(task.a, task.b):
            handle_mask(mask)

    elapsed = time.time() - t0
    ok = True
    if tried > 0 and failed == tried:
        ok = False

    return ChunkResult(
        ok=ok,
        task=task,
        ms=sorted(out),
        tried=tried,
        failed=failed,
        failed_masks=failed_masks,
        elapsed_sec=elapsed,
        err_samples=err_samples,
        masks_skipped_q_bound=masks_skipped_q_bound,
        masks_skipped_x1_bound=masks_skipped_x1_bound,
        masks_skipped_gp_bailout=masks_skipped_gp_bailout,
        iterates_early_break=iterates_early_break,
        candidates_skipped_nze=candidates_skipped_nze,
        nze_missing_prime_hist=nze_hist,
        nze_min_missing_count=nze_min_missing,
        nze_min_missing_m=nze_min_m,
    )


def filter_for_r(ms: List[int], r: int, primes: Tuple[int, ...]) -> List[int]:
    if r == 2:
        return ms
    out: List[int] = []
    for m in ms:
        if all(is_P_smooth(m + j, primes) for j in range(r)):
            out.append(m)
    return out


def compute_S_pmax_exact(
    primes: List[int],
    workers: int,
    r: int,
    nze_pruning: int,
    chunk_masks: int,
    striped: bool,
    incremental: bool,
    prior_S: Optional[List[int]],
    logf,
    gp_path: str,
    max_mask_attempts: int,
    mask_requeue_batch: int,
    gp_timeout: float,
    max_m: int = 0,
) -> Tuple[List[int], Dict[str, object], List[int]]:
    P = tuple(primes)
    omega = len(P)
    pmax = P[-1]
    L = max(3, pmax)
    nze_enabled = (nze_pruning > 0 and omega >= nze_pruning)

    total_masks = 1 << omega

    base_set: Set[int] = set()
    start_mask = 0
    end_mask = total_masks
    inc_used = False

    # NOTE: We do NOT restrict to the “new half” of masks at ω→ω+1.
    # Even if a new prime p_ω appears in m(m+1), it can occur with an even exponent
    # and therefore may be absent from the squarefree q used in D=2q (Pell). A classic
    # example is m=633555 at ω=8, where 19^2 divides m but 19 is absent from q.
    # Therefore, for correctness we always process the full mask range [0, 2^ω).
    # The prior_S list is still accepted for optional union/deduplication at output time.

    if incremental and prior_S is not None and omega >= 2:
        # When NZE pruning is enabled, we must not seed the current ω run with the
        # previous ω candidate list; those prior candidates may be non-prime-complete
        # for the larger prime set and would contaminate counts (and debugging).
        if not nze_enabled:
            base_set = set(prior_S)
            inc_used = True

    tasks: List[ChunkTask] = []
    step = 1
    if striped:
        step = max(1, workers * 64)
        window = end_mask - start_mask
        step = min(step, window) if window > 0 else 1
        tasks = [ChunkTask(offset=o) for o in range(step)]
    else:
        for a in range(start_mask, end_mask, chunk_masks):
            b = min(end_mask, a + chunk_masks)
            tasks.append(ChunkTask(a=a, b=b))

    params = WorkerParams(
        primes=P,
        L=L,
        r=r,
        nze_enabled=nze_enabled,
        start_mask=start_mask,
        end_mask=end_mask,
        striped=striped,
        step=step,
        gp_timeout=gp_timeout,
        max_m=max_m,
    )

    ctx = get_context("fork") if sys.platform == "darwin" else get_context()

    found: Set[int] = set(base_set)

    stats: Dict[str, object] = {
        "omega": omega,
        "pmax": pmax,
        "lehmer_L": L,
        "nze_pruning": nze_pruning,
        "nze_enabled": nze_enabled,
        "max_m": max_m,
        "incremental_used": inc_used,
        "start_mask": start_mask,
        "end_mask": end_mask,
        "striped": striped,
        "striped_step": step,
        "tasks_initial": len(tasks),
        "total_tried": 0,
        "total_failed": 0,
        "unique_failed_masks": 0,
        "unprocessed_masks": 0,
        "masks_skipped_q_bound": 0,
        "masks_skipped_x1_bound": 0,
        "masks_skipped_gp_bailout": 0,
        "iterates_early_break": 0,
        "candidates_skipped_nze": 0,
        # NZE diagnostics (only populated when DEBUG and nze_enabled)
        "nze_missing_prime_hist": {},
        "nze_min_missing_count": None,
        "nze_min_missing_m": None,
        "err_samples": [],
    }

    mask_attempts: Dict[int, int] = {}
    unprocessed: List[int] = []

    queue: List[ChunkTask] = list(tasks)
    done = 0
    total = len(queue)

    with ctx.Pool(
        processes=workers,
        initializer=_init_worker,
        initargs=(gp_path, DEBUG, ASSERTIONS),
    ) as pool:
        while queue:
            batch = queue[:workers * 8]
            queue = queue[workers * 8:]

            async_args = [(t, params) for t in batch]
            for res in pool.imap_unordered(worker_chunk, async_args, chunksize=1):
                done += 1
                stats["total_tried"] = int(stats["total_tried"]) + res.tried
                stats["total_failed"] = int(stats["total_failed"]) + res.failed
                stats["masks_skipped_q_bound"] = int(stats["masks_skipped_q_bound"]) + res.masks_skipped_q_bound
                stats["masks_skipped_x1_bound"] = int(stats["masks_skipped_x1_bound"]) + res.masks_skipped_x1_bound
                stats["masks_skipped_gp_bailout"] = int(stats["masks_skipped_gp_bailout"]) + res.masks_skipped_gp_bailout
                stats["iterates_early_break"] = int(stats["iterates_early_break"]) + res.iterates_early_break
                stats["candidates_skipped_nze"] = int(stats["candidates_skipped_nze"]) + getattr(res, "candidates_skipped_nze", 0)

                # Aggregate NZE diagnostics (DEBUG-only payloads)
                if getattr(res, "nze_missing_prime_hist", None):
                    hist = stats.get("nze_missing_prime_hist", {})
                    if not isinstance(hist, dict):
                        hist = {}
                    for p, c in res.nze_missing_prime_hist.items():
                        hist[p] = int(hist.get(p, 0)) + int(c)
                    stats["nze_missing_prime_hist"] = hist
                if getattr(res, "nze_min_missing_count", None) is not None:
                    cur = stats.get("nze_min_missing_count", None)
                    curm = stats.get("nze_min_missing_m", None)
                    nm = int(res.nze_min_missing_count)
                    nmm = int(res.nze_min_missing_m) if res.nze_min_missing_m is not None else None
                    if cur is None or nm < int(cur) or (nm == int(cur) and nmm is not None and (curm is None or nmm < int(curm))):
                        stats["nze_min_missing_count"] = nm
                        stats["nze_min_missing_m"] = nmm

                if res.err_samples:
                    es = stats.get("err_samples", [])
                    if isinstance(es, list) and len(es) < 80:
                        es.extend(res.err_samples)
                        stats["err_samples"] = es[:80]

                for m in res.ms:
                    found.add(m)

                if res.failed_masks:
                    for mask in res.failed_masks:
                        mask_attempts[mask] = mask_attempts.get(mask, 0) + 1
                        if mask_attempts[mask] >= max_mask_attempts:
                            unprocessed.append(mask)
                    retry_masks = [m for m in res.failed_masks if mask_attempts.get(m, 0) < max_mask_attempts]
                    if retry_masks:
                        for i in range(0, len(retry_masks), mask_requeue_batch):
                            queue.append(ChunkTask(masks=tuple(retry_masks[i:i + mask_requeue_batch])))
                            total += 1

                if done % 25 == 0 or not queue:
                    stats["unique_failed_masks"] = len(mask_attempts)
                    stats["unprocessed_masks"] = len(set(unprocessed))
                    logf.write(
                        f"{utc_now_iso()} progress chunks_done={done}/{total} "
                        f"cum_tried={stats['total_tried']} cum_failed={stats['total_failed']} "
                        f"unique_failed_masks={stats['unique_failed_masks']} "
                        f"unprocessed={stats['unprocessed_masks']} "
                        f"q_skipped={stats['masks_skipped_q_bound']} "
                        f"x1_skipped={stats['masks_skipped_x1_bound']} "
                        f"gp_bailout={stats['masks_skipped_gp_bailout']} "
                        f"iter_breaks={stats['iterates_early_break']} "
                        f"nze_skipped={stats['candidates_skipped_nze']}\n"
                    )
                    if DEBUG and nze_enabled and isinstance(stats.get("nze_missing_prime_hist"), dict) and stats["nze_missing_prime_hist"]:
                        # Log top missing primes (by frequency) among NZE-rejected candidates.
                        items = sorted(stats["nze_missing_prime_hist"].items(), key=lambda kv: (-int(kv[1]), int(kv[0])))
                        top = ",".join([f"{p}:{c}" for p, c in items[:10]])
                        logf.write(f"{utc_now_iso()} debug_nze_missing_top10={top} min_missing={stats.get('nze_min_missing_count')} at_m={stats.get('nze_min_missing_m')}\n")
                    if DEBUG and stats.get("err_samples"):
                        logf.write(f"{utc_now_iso()} debug_err_samples={stats['err_samples'][:5]}\n")
                    logf.flush()

    stats["unique_failed_masks"] = len(mask_attempts)
    stats["unprocessed_masks"] = len(set(unprocessed))

    return sorted(found), stats, sorted(set(unprocessed))


def compute_and_verify_lightweight(
    primes: List[int],
    r: int,
    nze_pruning: int,
    workers: int,
    chunk_masks: int,
    striped: bool,
    logf,
    gp_path: str,
    max_mask_attempts: int,
    mask_requeue_batch: int,
    gp_timeout: float,
    max_m: int = 0,
) -> Tuple[Dict[str, object], Dict[str, int], List[int]]:
    """Summary-only mode to avoid huge files and memory blow-ups for large ω.

    Enumerates P-smooth candidates (as produced by the Størmer/Lehmer Pell families),
    verifies each candidate on-the-fly for N_r(m), and returns only aggregated statistics.

    Returns: compute_stats, verify_stats, unprocessed_masks
    """
    P = tuple(primes)
    omega = len(P)
    pmax = P[-1]
    L = max(3, pmax)
    nze_enabled = (nze_pruning > 0 and omega >= nze_pruning)

    total_masks = 1 << omega
    start_mask = 0
    end_mask = total_masks

    # Build tasks
    tasks: List[ChunkTask] = []
    step = 1
    if striped:
        step = max(1, workers * 64)
        window = end_mask - start_mask
        step = min(step, window) if window > 0 else 1
        tasks = [ChunkTask(offset=o) for o in range(step)]
    else:
        for a in range(start_mask, end_mask, chunk_masks):
            b = min(end_mask, a + chunk_masks)
            tasks.append(ChunkTask(a=a, b=b))

    params = WorkerParams(
        primes=P,
        L=L,
        r=r,
        nze_enabled=nze_enabled,
        start_mask=start_mask,
        end_mask=end_mask,
        striped=striped,
        step=step,
        gp_timeout=gp_timeout,
        max_m=max_m,
    )

    ctx = get_context("fork") if sys.platform == "darwin" else get_context()

    compute_stats: Dict[str, object] = {
        "omega": omega,
        "pmax": pmax,
        "lehmer_L": L,
        "nze_pruning": nze_pruning,
        "nze_enabled": nze_enabled,
        "max_m": max_m,
        "incremental_used": False,
        "start_mask": start_mask,
        "end_mask": end_mask,
        "striped": striped,
        "striped_step": step,
        "tasks_initial": len(tasks),
        "total_tried": 0,
        "total_failed": 0,
        "unique_failed_masks": 0,
        "unprocessed_masks": 0,
        "masks_skipped_q_bound": 0,
        "masks_skipped_x1_bound": 0,
        "masks_skipped_gp_bailout": 0,
        "iterates_early_break": 0,
        "candidates_skipped_nze": 0,
        # NZE diagnostics (only populated when DEBUG and nze_enabled)
        "nze_missing_prime_hist": {},
        "nze_min_missing_count": None,
        "nze_min_missing_m": None,
        "err_samples": [],
        "S_raw_count": 0,
        "report_mode": "summary",
    }

    verify_stats: Dict[str, int] = {
        "count_m_S_pmax": 0,
        f"count_m_after_{r}_filter": 0,
        f"smooth_pass_{r}": 0,
        "pi_complete_hits": 0,
        "miss_star": 10**9,
        "miss_star_m": -1,
    }

    mask_attempts: Dict[int, int] = {}
    unprocessed: List[int] = []
    queue: List[ChunkTask] = list(tasks)
    done = 0
    total = len(queue)

    target = set(P)

    def _verify_one(m: int) -> None:
        # If NZE pruning is enabled in the worker, every emitted m already:
        #  (i) is P-smooth across all r multipliers, and
        # (ii) has full prime support P (no missing primes).
        # So each m is a prime-complete hit and we can update statistics without refactoring.
        if nze_enabled:
            verify_stats[f"count_m_after_{r}_filter"] += 1
            verify_stats[f"smooth_pass_{r}"] += 1
            verify_stats["pi_complete_hits"] += 1
            # miss_star is 0 by definition if any candidate exists
            if 0 < verify_stats["miss_star"]:
                verify_stats["miss_star"] = 0
                verify_stats["miss_star_m"] = m
            return

        fNr: Dict[int, int] = {}
        for j in range(r):
            mj = m + j
            fj, rem = factor_over_P(mj, P)
            if rem != 1:
                return
            fNr = factor_merge(fNr, fj)

        verify_stats[f"count_m_after_{r}_filter"] += 1
        verify_stats[f"smooth_pass_{r}"] += 1

        supp = support_tuple(fNr)
        supp_set = set(supp)
        if supp == P:
            verify_stats["pi_complete_hits"] += 1

        miss = len(target - supp_set)
        if miss < verify_stats["miss_star"]:
            verify_stats["miss_star"] = miss
            verify_stats["miss_star_m"] = m


    with ctx.Pool(
        processes=workers,
        initializer=_init_worker,
        initargs=(gp_path, DEBUG, ASSERTIONS),
    ) as pool:
        while queue:
            batch = queue[:workers * 8]
            queue = queue[workers * 8:]

            async_args = [(t, params) for t in batch]
            for res in pool.imap_unordered(worker_chunk, async_args, chunksize=1):
                done += 1
                compute_stats["total_tried"] = int(compute_stats["total_tried"]) + res.tried
                compute_stats["total_failed"] = int(compute_stats["total_failed"]) + res.failed
                compute_stats["masks_skipped_q_bound"] = int(compute_stats["masks_skipped_q_bound"]) + res.masks_skipped_q_bound
                compute_stats["masks_skipped_x1_bound"] = int(compute_stats["masks_skipped_x1_bound"]) + res.masks_skipped_x1_bound
                compute_stats["masks_skipped_gp_bailout"] = int(compute_stats["masks_skipped_gp_bailout"]) + res.masks_skipped_gp_bailout
                compute_stats["iterates_early_break"] = int(compute_stats["iterates_early_break"]) + res.iterates_early_break
                compute_stats["candidates_skipped_nze"] = int(compute_stats["candidates_skipped_nze"]) + getattr(res, "candidates_skipped_nze", 0)

                # Aggregate NZE diagnostics (DEBUG-only payloads)
                if getattr(res, "nze_missing_prime_hist", None):
                    hist = compute_stats.get("nze_missing_prime_hist", {})
                    if not isinstance(hist, dict):
                        hist = {}
                    for p, c in res.nze_missing_prime_hist.items():
                        hist[p] = int(hist.get(p, 0)) + int(c)
                    compute_stats["nze_missing_prime_hist"] = hist
                if getattr(res, "nze_min_missing_count", None) is not None:
                    cur = compute_stats.get("nze_min_missing_count", None)
                    curm = compute_stats.get("nze_min_missing_m", None)
                    nm = int(res.nze_min_missing_count)
                    nmm = int(res.nze_min_missing_m) if res.nze_min_missing_m is not None else None
                    if cur is None or nm < int(cur) or (nm == int(cur) and nmm is not None and (curm is None or nmm < int(curm))):
                        compute_stats["nze_min_missing_count"] = nm
                        compute_stats["nze_min_missing_m"] = nmm

                if res.err_samples:
                    es = compute_stats.get("err_samples", [])
                    if isinstance(es, list) and len(es) < 80:
                        es.extend(res.err_samples)
                        compute_stats["err_samples"] = es[:80]

                if res.ms:
                    compute_stats["S_raw_count"] = int(compute_stats["S_raw_count"]) + len(res.ms)
                    verify_stats["count_m_S_pmax"] += len(res.ms)
                    for mval in res.ms:
                        _verify_one(mval)

                if res.failed_masks:
                    for mask in res.failed_masks:
                        mask_attempts[mask] = mask_attempts.get(mask, 0) + 1
                        if mask_attempts[mask] >= max_mask_attempts:
                            unprocessed.append(mask)
                    retry_masks = [m for m in res.failed_masks if mask_attempts.get(m, 0) < max_mask_attempts]
                    if retry_masks:
                        for i in range(0, len(retry_masks), mask_requeue_batch):
                            queue.append(ChunkTask(masks=tuple(retry_masks[i:i + mask_requeue_batch])))
                            total += 1

                if done % 25 == 0 or not queue:
                    compute_stats["unique_failed_masks"] = len(mask_attempts)
                    compute_stats["unprocessed_masks"] = len(set(unprocessed))
                    logf.write(
                        f"{utc_now_iso()} progress chunks_done={done}/{total} "
                        f"cum_tried={compute_stats['total_tried']} cum_failed={compute_stats['total_failed']} "
                        f"unique_failed_masks={compute_stats['unique_failed_masks']} "
                        f"unprocessed={compute_stats['unprocessed_masks']} "
                        f"q_skipped={compute_stats['masks_skipped_q_bound']} "
                        f"x1_skipped={compute_stats['masks_skipped_x1_bound']} "
                        f"gp_bailout={compute_stats['masks_skipped_gp_bailout']} "
                        f"iter_breaks={compute_stats['iterates_early_break']} "
                        f"S_raw_count={compute_stats['S_raw_count']} "
                        f"pi_hits={verify_stats['pi_complete_hits']}\n"
                    )
                    if DEBUG and nze_enabled and isinstance(compute_stats.get("nze_missing_prime_hist"), dict) and compute_stats["nze_missing_prime_hist"]:
                        items = sorted(compute_stats["nze_missing_prime_hist"].items(), key=lambda kv: (-int(kv[1]), int(kv[0])))
                        top = ",".join([f"{p}:{c}" for p, c in items[:10]])
                        logf.write(f"{utc_now_iso()} debug_nze_missing_top10={top} min_missing={compute_stats.get('nze_min_missing_count')} at_m={compute_stats.get('nze_min_missing_m')}\n")
                    logf.flush()

    compute_stats["unique_failed_masks"] = len(mask_attempts)
    compute_stats["unprocessed_masks"] = len(set(unprocessed))

    if verify_stats["miss_star"] == 10**9:
        verify_stats["miss_star"] = -1

    return compute_stats, verify_stats, sorted(set(unprocessed))




@dataclass
class VerifyRow:
    m: int
    r: int
    Nr_support: Tuple[int, ...]
    Nr_factorization: str
    pi_complete: bool
    missing_from_P: Tuple[int, ...]
    extra_primes: Tuple[int, ...]


def verify_and_write_csv_stream(ms: List[int], primes: List[int], r: int, csv_path: str) -> Dict[str, int]:
    """Verify candidates and write verify CSV incrementally (streaming).

    This avoids storing all VerifyRow objects in memory.
    Returns the same verify_stats dictionary as prior versions.
    """
    P = tuple(primes)
    target = set(P)
    stats: Dict[str, int] = {
        "count_m_S_pmax": len(ms),
        f"count_m_after_{r}_filter": 0,
        f"smooth_pass_{r}": 0,
        "pi_complete_hits": 0,
    }

    with open(csv_path, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow([
            "m",
            "r",
            "Nr_prime_support",
            "Nr_factorization",
            "pi_complete_order_omega",
            "missing_from_target_support",
            "extra_primes",
        ])

        for m in ms:
            fNr: Dict[int, int] = {}
            for j in range(r):
                mj = m + j
                fj, rem = factor_over_P(mj, P)
                if rem != 1:
                    fNr = {}
                    break
                fNr = factor_merge(fNr, fj)

            if not fNr:
                continue

            stats[f"count_m_after_{r}_filter"] += 1
            stats[f"smooth_pass_{r}"] += 1

            supp = support_tuple(fNr)
            supp_set = set(supp)
            pi_ok = (supp == P)
            if pi_ok:
                stats["pi_complete_hits"] += 1

            w.writerow([
                m,
                r,
                ",".join(map(str, supp)),
                format_factorization(fNr),
                int(pi_ok),
                ",".join(map(str, sorted(target - supp_set))),
                ",".join(map(str, sorted(supp_set - target))),
            ])

    return stats


def verify_stream_lightweight(ms: List[int], primes: List[int], r: int) -> Dict[str, int]:
    """Verify candidates without writing per-m rows (summary-only mode).

    Tracks r-smooth count, π-hit count, and miss* (minimum missing primes).
    """
    P = tuple(primes)
    target = set(P)
    stats: Dict[str, int] = {
        "count_m_S_pmax": len(ms),
        f"count_m_after_{r}_filter": 0,
        f"smooth_pass_{r}": 0,
        "pi_complete_hits": 0,
        "miss_star": 10**9,
        "miss_star_m": -1,
    }

    for m in ms:
        fNr: Dict[int, int] = {}
        for j in range(r):
            mj = m + j
            fj, rem = factor_over_P(mj, P)
            if rem != 1:
                fNr = {}
                break
            fNr = factor_merge(fNr, fj)

        if not fNr:
            continue

        stats[f"count_m_after_{r}_filter"] += 1
        stats[f"smooth_pass_{r}"] += 1

        supp = support_tuple(fNr)
        supp_set = set(supp)
        if supp == P:
            stats["pi_complete_hits"] += 1

        miss = len(target - supp_set)
        if miss < stats["miss_star"]:
            stats["miss_star"] = miss
            stats["miss_star_m"] = m

    if stats["miss_star"] == 10**9:
        stats["miss_star"] = -1

    return stats
def write_summary_json(
    path: str,
    omega: int,
    r: int,
    primes: List[int],
    pmax: int,
    L: int,
    start_utc: str,
    end_utc: str,
    runtime_sec: float,
    env: Dict[str, object],
    workers: int,
    chunk_masks: int,
    striped: bool,
    incremental_used: bool,
    base_omega: Optional[int],
    s_file: str,
    verify_csv: str,
    log_file: str,
    unprocessed_file: Optional[str],
    compute_stats: Dict[str, object],
    verify_stats: Dict[str, int],
) -> None:
    summary = {
        "environment": env,
        "omega": omega,
        "r": r,
        "primes": primes,
        "pmax": pmax,
        "lehmer_L": L,
        # NZE pruning settings are recorded in compute_stats; repeat here for convenience.
        "nze_pruning": int(compute_stats.get("nze_pruning", 0) or 0),
        "nze_enabled": bool(compute_stats.get("nze_enabled", False)),
        "start_utc": start_utc,
        "end_utc": end_utc,
        "runtime_seconds": runtime_sec,
        "workers": workers,
        "chunk_masks": chunk_masks,
        "striped": striped,
        "incremental_used": incremental_used,
        "incremental_base_omega": base_omega,
        "compute_stats": compute_stats,
        "verify_stats": verify_stats,
        "artifacts": {
            "S_file": s_file,
            "S_file_sha256": sha256_file(s_file) if s_file and os.path.isfile(s_file) else None,
            "verify_csv": verify_csv,
            "verify_csv_sha256": sha256_file(verify_csv) if verify_csv and os.path.isfile(verify_csv) else None,
            "log_file": log_file,
            "log_file_sha256": sha256_file(log_file),
            "unprocessed_file": unprocessed_file,
            "unprocessed_file_sha256": sha256_file(unprocessed_file) if unprocessed_file and os.path.isfile(unprocessed_file) else None,
        },
        "complete_enumeration": (int(compute_stats.get("unprocessed_masks", 0)) == 0),
    }
    with open(path, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2, sort_keys=True)


def omega_dir(outdir: str, omega: int, r: int) -> str:
    return os.path.join(outdir, f"r_{r}", f"omega_{omega:02d}")

def omega_done(outdir: str, omega: int, r: int) -> bool:
    return os.path.isfile(os.path.join(omega_dir(outdir, omega, r), f"summary_r{r}_omega_{omega:02d}.json"))


def main() -> None:
    global DEBUG, ASSERTIONS

    ap = argparse.ArgumentParser()
    ap.add_argument('--version', action='store_true', help='Print version/environment info and exit')
    ap.add_argument("--outdir", default=f"{program_name}_v{program_version}_audit_runs")
    ap.add_argument("--runlength", type=int, default=2, choices=[2, 3, 4, 5])
    ap.add_argument("--start_omega", type=int, default=8)
    ap.add_argument("--end_omega", type=int, default=20)
    ap.add_argument("--full_report_omega_max", type=int, default=20,
                    help="Write full artifacts (S-list + verify CSV) only for ω ≤ this value. "
                         "For ω above this threshold, run in summary-only mode to avoid huge files.")
    ap.add_argument("--nze_pruning", type=int, default=0,
                    help="Enable NZE (no-zero-exponent / prime-complete) pruning in the Pell inner loop for ω ≥ this threshold." \
                         + " When enabled, workers only emit candidates that already cover every prime in P_ω (no missing primes)." \
                             + " 0 = disabled. For referee-grade full reporting, keep this at 0 or set it above --full_report_omega_max.")
    ap.add_argument("--workers", type=int, default=0)
    ap.add_argument("--chunk_masks", type=int, default=32)
    ap.add_argument("--striped", action="store_true")
    ap.add_argument("--no_incremental", action="store_true")
    ap.add_argument("--gp_path", default="gp")
    ap.add_argument("--max_mask_attempts", type=int, default=8)
    ap.add_argument("--mask_requeue_batch", type=int, default=64)
    ap.add_argument("--gp_timeout", type=float, default=0.0)
    ap.add_argument("--max_m", type=int, default=0,
                    help="Upper bound on m for early rejection. "
                         "Masks where q > 2*max_m*(max_m+1) are skipped (no GP call). "
                         "Iterate loops break when m > max_m. "
                         "0 = disabled (full enumeration, no skipping). "
                         "When set, the enumeration is provably complete up to max_m: "
                         "from x^2 - 2qy^2 = 1 with y >= 1, x >= sqrt(2q+1), "
                         "so m = (x-1)/2 >= (sqrt(2q+1)-1)/2 > max_m when q > 2*max_m*(max_m+1).")
    ap.add_argument("--debug", action="store_true")
    ap.add_argument("--assertions", action="store_true")
    args = ap.parse_args()

    # Version/env reporting (for reproducible certification)
    if args.version:
        info = env_block(args.gp_path, __file__, sys.argv)
        print(json.dumps(info, indent=2, sort_keys=True))
        return

    DEBUG = bool(args.debug)
    ASSERTIONS = bool(args.assertions)

    # Capture environment + script identity for audit trail.
    global ENV
    ENV = env_block(args.gp_path, __file__, sys.argv)

    outdir = args.outdir
    r = args.runlength
    ensure_dir(os.path.join(outdir, f"r_{r}"))

    workers = args.workers if args.workers and args.workers > 0 else (os.cpu_count() or 1)

    # check gp executable
    try:
        subprocess.run([args.gp_path, "-q"], input="print(1);\nquit\n",
                       text=True, capture_output=True, check=True)
    except Exception:
        print("[!] Could not run gp. Pass --gp_path /opt/homebrew/bin/gp (or your path).")
        raise

    print(f"[+] Using gp-based Pell: YES (pellxy defined; no bnfnorm)")
    print(f"[+] outdir: {outdir}")
    print(f"[+] runlength={r} count of multipliers: {2}..{5}")
    print(f"[+] full_report_omega_max={args.full_report_omega_max} (summary-only for ω above this)")
    print(f"[+] workers={workers} chunk_masks={args.chunk_masks} striped={args.striped}")
    print(f"[+] incremental={not args.no_incremental} gp_path={args.gp_path}")
    print(f"[+] max_m={args.max_m}" + (" (early rejection enabled)" if args.max_m > 0 else " (disabled, full enumeration)"))
    print(f"[+] debug={DEBUG} assertions={ASSERTIONS}")
    print(f"[+] start time (UTC): {utc_now_iso()}\n")

    for omega in range(args.start_omega, args.end_omega + 1):
        d = omega_dir(outdir, omega, r)
        ensure_dir(d)
        if omega_done(outdir, omega, r):
            print(f"[=] omega={omega}: already done, skipping.")
            continue

        primes = primes_first_n(omega)
        pmax = primes[-1]
        L = max(3, pmax)

        s_path = os.path.join(d, f"S_p{pmax}_r{r}_omega_{omega:02d}.txt")
        v_path = os.path.join(d, f"verify_r{r}_omega_{omega:02d}.csv")
        summary_path = os.path.join(d, f"summary_r{r}_omega_{omega:02d}.json")
        log_path = os.path.join(d, f"run_r{r}_omega_{omega:02d}.log")
        unproc_path = os.path.join(d, f"unprocessed_masks_r{r}_omega_{omega:02d}.txt")
        full_mode = (omega <= args.full_report_omega_max)
        # For ω above the threshold, run in summary-only mode and avoid large artifacts.

        prior_S: Optional[List[int]] = None
        base_omega: Optional[int] = None
        if full_mode and (not args.no_incremental) and omega > 1:
            prev_dir = omega_dir(outdir, omega - 1, r)
            prev_primes = primes_first_n(omega - 1)
            prev_pmax = prev_primes[-1]
            prev_s = os.path.join(prev_dir, f"S_p{prev_pmax}_r{r}_omega_{omega-1:02d}.txt")
            prev_summary = os.path.join(prev_dir, f"summary_r{r}_omega_{omega-1:02d}.json")
            if os.path.isfile(prev_s) and os.path.isfile(prev_summary):
                prior_S = load_int_list(prev_s)
                base_omega = omega - 1

        start_utc = utc_now_iso()
        t0 = time.time()

        with open(log_path, "a", encoding="utf-8") as logf:
            logf.write(
                f"{start_utc} START r={r} omega={omega} primes={primes} workers={workers} "
                f"chunk_masks={args.chunk_masks} striped={args.striped} "
                f"incremental={not args.no_incremental} base_omega={base_omega} "
                f"max_mask_attempts={args.max_mask_attempts} max_m={args.max_m} "
                f"debug={DEBUG} assertions={ASSERTIONS}\n"
            )
            logf.flush()

            try:
                # Choose reporting mode based on ω threshold.
                if full_mode:
                    # Full artifacts for certification range (ω ≤ full_report_omega_max)
                    S_list, compute_stats, unprocessed = compute_S_pmax_exact(
                        primes=primes,
                        r=r,
                        nze_pruning=args.nze_pruning,
                        workers=workers,
                        chunk_masks=args.chunk_masks,
                        striped=args.striped,
                        incremental=(not args.no_incremental),
                        prior_S=prior_S,
                        logf=logf,
                        gp_path=args.gp_path,
                        max_mask_attempts=args.max_mask_attempts,
                        mask_requeue_batch=args.mask_requeue_batch,
                        gp_timeout=args.gp_timeout,
                        max_m=args.max_m,
                    )

                    Ptuple = tuple(primes)
                    S_r = filter_for_r(S_list, r=r, primes=Ptuple)
                    write_int_list(s_path, S_r)

                    verify_stats = verify_and_write_csv_stream(S_r, primes, r=r, csv_path=v_path)
                    compute_stats['report_mode'] = 'full'
                else:
                    # Summary-only mode: stream verification and do not write S/verify files.
                    compute_stats, verify_stats, unprocessed = compute_and_verify_lightweight(
                        primes=primes,
                        r=r,
                        nze_pruning=args.nze_pruning,
                        workers=workers,
                        chunk_masks=args.chunk_masks,
                        striped=args.striped,
                        logf=logf,
                        gp_path=args.gp_path,
                        max_mask_attempts=args.max_mask_attempts,
                        mask_requeue_batch=args.mask_requeue_batch,
                        gp_timeout=args.gp_timeout,
                        max_m=args.max_m,
                    )
                    S_list = []
                    S_r = []

                S_raw_ct = (len(S_list) if full_mode else int(compute_stats.get('S_raw_count', 0)))
                S_r_ct = (len(S_r) if full_mode else int(verify_stats.get(f'count_m_after_{r}_filter', 0)))
                unprocessed_file: Optional[str] = None
                if unprocessed:
                    unprocessed_file = unproc_path
                    with open(unproc_path, "w", encoding="utf-8") as f:
                        f.write("# mask\tq(mask)\tD=2*q\n")
                        P = tuple(primes)
                        for mask in unprocessed:
                            q = 1
                            mm = mask
                            i = 0
                            while mm:
                                if mm & 1:
                                    q *= P[i]
                                mm >>= 1
                                i += 1
                            f.write(f"{mask}\t{q}\t{2*q}\n")

                end_utc = utc_now_iso()
                runtime = time.time() - t0

                write_summary_json(
                    path=summary_path,
                    omega=omega,
                    r=r,
                    primes=primes,
                    pmax=pmax,
                    L=L,
                    start_utc=start_utc,
                    end_utc=end_utc,
                    runtime_sec=runtime,
                    env=ENV,
                    workers=workers,
                    chunk_masks=args.chunk_masks,
                    striped=args.striped,
                    incremental_used=bool(compute_stats["incremental_used"]),
                    base_omega=base_omega if compute_stats["incremental_used"] else None,
                    s_file=(s_path if full_mode else ""),
                    verify_csv=(v_path if full_mode else ""),
                    log_file=log_path,
                    unprocessed_file=unprocessed_file,
                    compute_stats=compute_stats,
                    verify_stats=verify_stats,
                )

                logf.write(
                    f"{end_utc} DONE r={r} omega={omega} |S_raw|={S_raw_ct} |S_{r}|={S_r_ct} "
                    f"pi_hits={verify_stats['pi_complete_hits']} unprocessed_masks={len(unprocessed)} "
                    f"runtime_sec={runtime:.3f}\n"
                )
                logf.flush()

                print(f"[>] omega={omega} pmax={pmax} L={L} "
                      f"|S_raw|={S_raw_ct} |S_{r}|={S_r_ct} "
                      f"pi_hits={verify_stats['pi_complete_hits']} "
                      f"unprocessed={len(unprocessed)} runtime={runtime/60:.2f} min")
            except Exception as e:
                end_utc = utc_now_iso()
                logf.write(f"{end_utc} ERROR runlength={r} omega={omega} error={repr(e)}\n")
                logf.flush()
                print(f"[!] ERROR omega={omega}: {e!r} (see {log_path})")

    print(f"[+] Finished. End time (UTC): {utc_now_iso()}")


if __name__ == "__main__":
    if sys.platform == "darwin":
        try:
            import multiprocessing as mp
            mp.set_start_method("fork")
        except RuntimeError:
            pass
    main()